package config

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

type Config struct {
	CEL                 CEL    `yaml:"cel,omitempty"`
	QueueName           string `yaml:"queueName" `
	MultiClusterEnabled bool   `yaml:"multi-cluster-enabled" `
	MultiClusterRole    string `yaml:"multi-cluster-role"`
}

type CEL struct {
	Expressions []string `yaml:"expressions,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
// This function is used by operator at the time of upgrade to deepcopy the config
func (in *CEL) DeepCopyInto(out *CEL) {
	*out = *in
	if in.Expressions != nil {
		in, out := &in.Expressions, &out.Expressions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}
