---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/konflux-ci/kueue-external-admission/config/default?ref=96beaf5c2e564560ebe469ffc16cca5220c14e82
- admission-check.yaml

images:
- name: example.com/alert-manager-kueue-admission
  newName: quay.io/konflux-ci/kueue-external-admission
  newTag: 96beaf5c2e564560ebe469ffc16cca5220c14e82

namespace: kueue-external-admission

patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: config
    patch: |-
      - op: replace
        path: /data/shouldAdmit
        value: "true"
