---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ResourceFlavor
metadata:
  name: "default-flavor"

---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: cluster-pipeline-queue
spec:
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO
  admissionChecks:
    - static-admission
  resourceGroups:
  - coveredResources:
    - "memory"
    - "tekton.dev/pipelineruns"
    - "ppc64-small"
    - "arm64-small"
    flavors:
    - name: "default-flavor"
      resources:
      - name: "memory"
        nominalQuota: 1Gi
      - name: "tekton.dev/pipelineruns"
        nominalQuota: 3
      - name: "ppc64-small"
        nominalQuota: 2
      - name: "arm64-small"
        nominalQuota: 2
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: pipelines-queue
spec:
  clusterQueue: cluster-pipeline-queue

---
# block running pipelines by setting the nominalQuota to 0
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: blocking-cluster-pipeline-queue
spec:
  namespaceSelector: {}
  queueingStrategy: BestEffortFIFO
  resourceGroups:
  - coveredResources: ["tekton.dev/pipelineruns"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "tekton.dev/pipelineruns"
        nominalQuota: 0
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: LocalQueue
metadata:
  name: blocking-pipelines-queue
spec:
  clusterQueue: blocking-cluster-pipeline-queue
